// Stub types for Hydrogen codegen outputs
// These would be auto-generated by `shopify hydrogen codegen` in production

declare module 'storefrontapi.generated' {
  import type {I18nBase} from '@shopify/hydrogen/storefront-api-types';

  export type StorefrontApi = Record<string, unknown>;
  export type I18n = I18nBase;

  export interface HeaderQuery {
    shop: {
      id: string;
      name: string;
      description: string | null;
      primaryDomain: {url: string};
      brand: {logo: {url: string; width: number; height: number; altText: string | null} | null} | null;
    };
    menu: {
      id: string;
      items: Array<{
        id: string;
        resourceId: string | null;
        tags: string[];
        title: string;
        type: string;
        url: string;
        items: Array<Record<string, unknown>>;
      }>;
    } | null;
  }

  export interface FooterQuery {
    menu: {
      id: string;
      items: Array<{
        id: string;
        resourceId: string | null;
        tags: string[];
        title: string;
        type: string;
        url: string;
        items: Array<Record<string, unknown>>;
      }>;
    } | null;
  }

  export interface CartApiQueryFragment {
    id: string;
    totalQuantity: number;
    checkoutUrl: string;
    cost: {
      subtotalAmount: {amount: string; currencyCode: string};
      totalAmount: {amount: string; currencyCode: string};
      totalTaxAmount: {amount: string; currencyCode: string};
    };
    lines: {nodes: Array<Record<string, unknown>>};
    discountCodes: Array<Record<string, unknown>>;
    buyerIdentity: {
      email: string | null;
      phone: string | null;
      customer: {id: string} | null;
      countryCode: string | null;
    };
    attributes: Array<{key: string; value: string}>;
    note: string | null;
    createdAt: string;
    updatedAt: string;
  }

  export interface FeaturedCollectionFragment {
    id: string;
    title: string;
    image: {
      id: string;
      url: string;
      altText: string | null;
      width: number;
      height: number;
    } | null;
    handle: string;
  }

  export interface RecommendedProductsQuery {
    products: {
      nodes: Array<{
        id: string;
        title: string;
        handle: string;
        vendor: string | null;
        tags: string[];
        priceRange: {
          minVariantPrice: {amount: string; currencyCode: string};
        };
        compareAtPriceRange: {
          minVariantPrice: {amount: string; currencyCode: string} | null;
        };
        featuredImage: {
          id: string;
          url: string;
          altText: string | null;
          width: number;
          height: number;
        } | null;
      }>;
    };
  }
}

declare module 'customer-accountapi.generated' {
  export type CustomerAccountApi = Record<string, unknown>;
}
